### ISSUE TITLE
support sink configuration through xml/json 

### ISSUE THREAD

**Issue by tanmaya-panda1** [saguiitay/serilog-sinks-azuredataexplorer#12]
We added configuration through appsetting.json as mentioned in https://github.com/Azure/serilog-sinks-azuredataexplorer.
sample settings are already provided in the readme.

```[tasklist]
### Tasks
- [x] provide info in Readme for additional properties which can be supported through appsettings.json
- [x] add support for configuration using xml
- [x] add sample for configuration using json
- [x] add testcases for json support (https://github.com/Azure/serilog-sinks-azuredataexplorer/issues/26)
- [x] add testcases for xml support
- [x] add details in Readme for xml based config
- [x] modify the sample to use userToken based authentication instead of clientSecret credentials
- [x] add complete details about Perodic Batching in Readme
- [x] periodic batching sink was imported by default in serilog, doesnt need to included explictly- necessary changes needs to be done
```
